config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "home#index" 
  # Defines the root path route ("/")
  # root "articles#index"
  resources :products

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products, dependent: :nullify
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    belongs_to :category
  
    validates :name, presence: true
    validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end
  

app/models/user.rb
class User < ApplicationRecord
    # Don't manually define `password_digest`
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable
    # ...
    has_secure_password
    has_many :products, dependent: :destroy
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
      render
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
  
    def index
      @products = Product.all
    end
  
    def show
      @product = Product.find(params[:id])
    end
  
    def new
      @product = Product.new
    end
  
    def create
      @product = current_user.products.build(product_params)
      if @product.save
        redirect_to @product, notice: 'Product was successfully created.'
      else
        render :new
      end
    end
  
    private
  
    def product_params
      params.require(:product).permit(:name, :description, :quantity, :category_id)
    end
end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %> 
 <div> Welcome <%= current_user.email %> </div> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
<% end %>
<h1>Video Production Inventory</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoProductionInventory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= form_with(model: @product, url: products_path, local: true) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :description %>
  <%= form.text_area :description %>

  <%= form.label :quantity %>
  <%= form.number_field :quantity %>

  <%= form.label :category_id %>
  <%= form.collection_select :category_id, Category.all, :id, :name %>

  <%= form.submit 'Create Product' %>
<% end %>

<%= link_to 'Back', products_path %>